# @package _group_
name: metaworld-mt10
num_envs: 10
use_onehot: False # whether add one-hot encoding to the observation
use_kuka_env: False # whether train on KUKA or Sawyer (default False using Sawyer)
benchmark:
  _target_: metaworld.MT10
kuka_benchmark:
  _target_: metaworld.MT10_KUKA
builder:
  make_kwargs:
    should_perform_reward_normalization: True
dummy:
  _target_: metaworld.MT1
  env_name: pick-place-v1
description:
  reach-v1: Reach a goal position. Randomize the goal positions.
  push-v1: Push the puck to a goal. Randomize puck and goal positions.
  pick-place-v1: Pick and place a puck to a goal. Randomize puck and goal positions.
  door-open-v1: Open a door with a revolving joint. Randomize door positions.
  faucet-open-v1: Rotate the faucet counter-clockwise. Randomize faucet positions.
  drawer-close-v1: Push and close a drawer. Randomize the drawer positions.
  button-press-topdown-v1: Press a button from the top. Randomize button positions.
  peg-unplug-side-v1: Unplug a peg sideways. Randomize peg positions.
  window-open-v1: Push and open a window. Randomize window positions.
  window-close-v1: Push and close a window. Randomize window positions.
ordered_task_list: # will be auto-populated.
